version: "3.9"

services:
  db:
    image: postgres:12.15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=devster
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data: