version: "3.4"

services:
  db:
    image: postgres:12.15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=devster
      - POSTGRES_PASSWORD=postgres
  backend:
    image: dvstr-backend
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/dvstr/static/
      - media_volume:/dvstr/media/
  nginx:
    image: nginx:1.24.0-alpine
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # certbot
      - ./certbot/conf/:/etc/letsencrypt/
      - ./certbot/www/:/var/www/certbot/
      # django static
      - static_volume:/dvstr/static/
      - media_volume:/dvstr/media/
    depends_on:
      - backend
      - certbot
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/
      - ./certbot/www/:/var/www/certbot/

volumes:
  postgres_data:
  static_volume:
  media_volume:
