# Generated by Django 3.2.16 on 2023-02-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='_', max_length=150),
            preserve_default=False,
        ),
    ]
