# Generated by Django 3.2.16 on 2022-12-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardsession',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
