# Generated by Django 3.2.16 on 2022-12-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0004_auto_20221225_1745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlashCard',
            new_name='Card',
        ),
        migrations.RenameModel(
            old_name='SessionAnswer',
            new_name='SessionCardAnswer',
        ),
    ]
