# Generated by Django 3.2.16 on 2023-02-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='_', upload_to='blog-images/'),
            preserve_default=False,
        ),
    ]
