# Generated by Django 3.2.16 on 2022-12-25 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0002_alter_flashcardsession_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(editable=False)),
                ('end_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flash_cards.flashcard')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flash_cards.session')),
            ],
        ),
        migrations.RenameModel(
            old_name='FlashCardModule',
            new_name='Module',
        ),
        migrations.AlterUniqueTogether(
            name='flashcardsessionanswer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='flashcardsessionanswer',
            name='card',
        ),
        migrations.RemoveField(
            model_name='flashcardsessionanswer',
            name='session',
        ),
        migrations.DeleteModel(
            name='FlashCardSession',
        ),
        migrations.DeleteModel(
            name='FlashCardSessionAnswer',
        ),
        migrations.AddField(
            model_name='session',
            name='answers',
            field=models.ManyToManyField(related_name='sessions', through='flash_cards.SessionAnswer', to='flash_cards.FlashCard'),
        ),
    ]
