# Generated by Django 3.2.16 on 2023-02-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0007_alter_card_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='flash_cards.Module'),
        ),
    ]
