# Generated by Django 4.2.3 on 2023-07-29 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeInList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_list_item', to='recipes.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='recipes.recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('date', 'type', 'owner')},
        ),
        migrations.CreateModel(
            name='RecipeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_lists', to=settings.AUTH_USER_MODEL)),
                ('recipes', models.ManyToManyField(through='recipes.RecipeInList', to='recipes.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipeinlist',
            name='recipe_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_list_item', to='recipes.recipelist'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeinlist',
            unique_together={('recipe', 'recipe_list')},
        ),
    ]
